module.exports = {
  TWITCH_CLIENT_ID: 'TWITCH_CLIENT_ID',
  TWITCH_CLIENT_SECRET: 'TWITCH_CLIENT_SECRET',
  TWITCH_CALLBACK_URL: 'TWITCH_CALLBACK_URL',
  MONGO_URI: 'YOUR_MONGO_URI',
  SESSION_SECRET: 'YOUR_SESSION_SECRET'
};
